#@ load("@ytt:data", "data")
#@ def in_list(key, list):
#@  return hasattr(data.values.tap_values, key) and (data.values.tap_values[key] in list)
#@ end
#@ if/end in_list('supply_chain', ['testing', 'testing_scanning']) and in_list('profile', ['full', 'iterate', 'run']):
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  annotations:
    rabbitmq.com/topology-allowed-namespaces: '*'
  name: rmq-where-for-dinner
spec:
  replicas: 1
  resources:
    requests:
      cpu: 200m
    limits:
      cpu: 200m
 
